= Backstage Workshop

To learn about the Software Templates that were used in this workshop, explore the `scaffolder-templates` folder. For additional Template examples, see https://github.com/janus-idp/software-templates

== Workshop Content Development

==== Local Development with Gulp
Install local development dependencies via `npm`:

```bash
npm install
```

Launch a local development server:

```bash
npm start
```

==== Promoting your changes

Add and commit your changes, then run `git push` to trigger a new deployment:

```bash
git push origin master
```

== Workshop Cluster Setup

To set up your own workshop cluster, implement the following changes to the link:https://janus-idp.io/demo-setup/install/[demo-setup] installation process:

1. When asked to clone the `janus-idp/demo-setup` repo, create a checkout of this `workshop` branch instead:
+
```bash
git clone https://github.com/ryanj/janus-platforms.git
cd janus-platforms/ansible/cluster-setup
git checkout workshop
```
2. When asked to fork the `janus-idp/software-templates` repo to your new GH Org, fork this repo instead: `https://github.com/redhat-scholars/backstage-workshop`.  Make sure to change the name of the resulting repo to: `software-templates`
3. After creating your new GH Org, visit the `org/settings/member_privileges` admin page, and change the Base permissions for all repos to "Write"
+
```bash
open "https://github.com/organizations/$GITHUB_ORGANIZATION/settings/member_privileges/"
```

If you a using a ROSA cluster that is configured to use GH Auth for cluster access, proceed to the next section to install the Namespace Configuration Operator

=== Installing the Namespace Configuration Operator (Optional)

WARNING: This section is NOT intended for RHPD users!  This section is ONLY for ROSA users who have configured GH Auth as their primary authentication scheme!

1. *Optionally,* install the CoP Namespace Configuration Operator from OperatorHub:
+
```bash
oc new-project namespace-configuration-operator
oc create -f https://raw.githubusercontent.com/redhat-cop/namespace-configuration-operator/master/config/operatorhub/operator.yaml
```
2. Wait for the operator installation to complete...
3. After the operator installation has completed, install the following `UserConfig` yaml:
+
```bash
cat <<EOF | oc create -f -
kind: UserConfig
apiVersion: redhatcop.redhat.io/v1alpha1
metadata:
  name: test-user-config
spec:
  annotationSelector: {}
  identityExtraFieldSelector: {}
  labelSelector: {}
  providerName: GitHub
  templates:
    - excludedPaths:
        - .spec.replicas
        - .metadata
        - .status
      objectTemplate: |
        - apiVersion: project.openshift.io/v1
          kind: Project
          metadata:
            name: {{ .Name }}
        - apiVersion: rbac.authorization.k8s.io/v1
          kind: RoleBinding
          metadata:
            name: {{ .Name }}-rolebinding
            namespace: {{ .Name }}
          roleRef:
            apiGroup: rbac.authorization.k8s.io
            kind: ClusterRole
            name: admin
          subjects:
          - apiGroup: rbac.authorization.k8s.io
            kind: User
            name: {{ .Name }}
EOF
```
