= Backstage Workshop featuring RHDH and GitHub

To learn about the Software Templates that were used in this workshop, explore the `scaffolder-templates` folder. For additional Template examples, see https://github.com/janus-idp/software-templates

== Workshop Cluster Setup

To set up your own workshop cluster, implement the following changes to the link:https://janus-idp.io/demo-setup/install/[demo-setup] installation process:

1. First, create a checkout of link:https://github.com/ryanj/janus-platforms/tree/workshop[this `workshop` branch] (instead of using the `janus-idp/demo-setup` repo):
+
```bash
git clone https://github.com/ryanj/janus-platforms.git
cd janus-platforms/ansible/cluster-setup
git checkout workshop
```
2. Next, link:https://github.com/redhat-scholars/backstage-workshop/fork[fork this repo] into your new github org and set the name of the new repo to: `software-templates`
3. Then, complete the rest of the link:https://janus-idp.io/demo-setup/install/[demo-setup] installation process (while skipping the optional quay section).  That doc will instuct you to export several variables that will be used in the upcoming example commands.
4. Visit the `org/settings/member_privileges` admin page, and change the Base permissions for all repos to "Write"
+
```bash
open "https://github.com/organizations/$GITHUB_ORGANIZATION/settings/member_privileges/"
```
5. Create *another* OAuth app to provide GitHub Auth into the Openshift cluster:
+
```bash
open "https://github.com/organizations/$GITHUB_ORGANIZATION/settings/applications/new/?oauth_application[name]=$GITHUB_ORGANIZATION-auth&oauth_application[url]=https://oauth-openshift.apps$OPENSHIFT_CLUSTER_INFO&oauth_application[callback_url]=https://oauth-openshift.apps$OPENSHIFT_CLUSTER_INFO/oauth2callback/github"
```
6. Configure your new GitHub OAuth App's `id` and `secret`, and add your gh org to the list of approved orgs:
+
```bash
open "https://console-openshift-console.apps$OPENSHIFT_CLUSTER_INFO/settings/idp/github"
```
7. Install the CoP Namespace Configuration Operator from OperatorHub:
+
```bash
oc new-project namespace-configuration-operator
oc create -f https://raw.githubusercontent.com/redhat-cop/namespace-configuration-operator/master/config/operatorhub/operator.yaml
# wait for the operator installation to complete...
sleep 60
cat <<EOF | oc create -f -
kind: UserConfig
apiVersion: redhatcop.redhat.io/v1alpha1
metadata:
  name: test-user-config
spec:
  annotationSelector: {}
  identityExtraFieldSelector: {}
  labelSelector: {}
  providerName: github
  templates:
    - excludedPaths:
        - .spec.replicas
        - .metadata
        - .status
      objectTemplate: |
        - apiVersion: project.openshift.io/v1
          kind: Project
          metadata:
            name: {{ .Name }}
        - apiVersion: rbac.authorization.k8s.io/v1
          kind: RoleBinding
          metadata:
            name: {{ .Name }}-rolebinding
            namespace: {{ .Name }}
          roleRef:
            apiGroup: rbac.authorization.k8s.io
            kind: ClusterRole
            name: admin
          subjects:
          - apiGroup: rbac.authorization.k8s.io
            kind: User
            name: {{ .Name }}
EOF
```
8. Switch from xref:#janus-to-rhdh[Janus to RHDH] (see below)
9. Increase cluster capacity by scaling up machineSets (if needed):
+
```bash
open "https://console-openshift-console.apps$OPENSHIFT_CLUSTER_INFO/k8s/ns/openshift-machine-api/machine.openshift.io~v1beta1~MachineSet"
```
10. Share access by inviting users to your github org. Users will need to accept the invite before accessing the cluster:
+
```bash
open "https://github.com/orgs/$GITHUB_ORGANIZATION/people"
```

TIP: For larger workshops you can optionally link:https://gist.github.com/ryanj/47da864d6f892bbb86deb918232d1d14[upload your list of new users using a script]

=== Janus to RHDH

To switch to the latest RHDH image, you will need to complete the folowing:

 1. Request access to the following quay repo: `quay.io/rhdh/developer-hub-rhel9`.  Requests from Internal Red Hatters should be sent to rhdh@redhat.com.  Requests from customers should be sent to rhdh-interest@redhat.com.
 2. After gaining access to the quay repo.  Visit https://quay.io and click on Profile -> Account Settings -> Robot Accounts -> Create Robot Account
 3. Name the Robot Account "rhdh_pull_secret".
 4. Open your robot account and select the "Kubernetes Secret" tab.  Download your pull secret yaml.
 5. Edit your pull secret yaml, setting the pull secret's `metadata.name` field to: `rhdh-pull-secret`
 6. Install your pull secret in the backstage namespace: 
+
```bash
kubectl create -f secret.yaml -n backstage
```
 7. Update the janus deployment to reference the new image pull secret: 
+
```bash
kubectl patch deploy/janus-dev -n backstage -p '{"spec":{"template":{"spec":{"imagePullSecrets":[{"name":"rhdh-pull-secret"}],"containers":[{"name":"janus-backstage","image":"quay.io/rhdh/developer-hub-rhel9:0.1"}]}}}}'
```

== Workshop Content Development

workshop content is available at: https://redhat-scholars.github.io/backstage-workshop

==== Local Development with Gulp
Install local development dependencies via `npm`:

```bash
npm install
```

Launch a local development server:

```bash
npm start
```

==== Promoting your changes

Add and commit your changes, then run `git push` to trigger a new deployment:

```bash
git push origin master
```
