= Development
include::_attributes.adoc[]

[#configuration]
== Service Binding and Configuration

Connect to a terminal on the gateway pod

1. List gateway backends:
+
[.console-input]
[source,bash,subs="+macros,+attributes"]
----
curl localhost:8080/backend/list
----

2. Register your new backend service:
+
[.console-input]
[source,bash,subs="+macros,+attributes"]
----
curl localhost:8080/backend/register/poi-backend?endpoint=http://poi-backend-app:8080
----

3. List gateway backends:
+
[.console-input]
[source,bash,subs="+macros,+attributes"]
----
curl localhost:8080/backend/list
----

4. Check the backend database for records. The result should be empty:
+
[.console-input]
[source,bash,subs="+macros,+attributes"]
----
curl http://poi-backend-app:8080/ws/data/all
----

5. Populate the backend database:
+
[.console-input]
[source,bash,subs="+macros,+attributes"]
----
curl http://poi-backend-app:8080/ws/data/load
----

6. Check the backend database for new records:
+
[.console-input]
[source,bash,subs="+macros,+attributes"]
----
curl http://poi-backend-app:8080/ws/data/all
----

Check the map for results!

[#devspaces]
== Introducing DevSpaces

[#gateway_update]
== Update the Gateway Service
Open the Gateway component in DevSpaces

When prompted, make sure to “Grant” access to your team's GitHub Org when approving DevSpaces access via GH Auth!

Open `/src/main/java/com/rhdevelopers/summit/workshop/SummitBackendResource.java`

Uncomment the following code block near the bottom of the file:

[.console-input]
[source,java,subs="+macros,+attributes"]
----
    @POST
    @Path("poi/add/point")
    public Response loadCustomPoi(PoiRecord record) {
        SUMMIT_POI_RECORDS.add(record);
        return Response.created(
            UriBuilder.fromPath("fake/poi/find/"+(SUMMIT_POI_RECORDS.size()-1)).build()
        ).entity("inserted custom data point").build();
    }
----

Commit your change and sync

Check the resulting pipelines and deployments for activity

Verify that your change has been published

[#validate_your_change]
== Validate your Changes

Connect to the gateway pod to load a new datapoint:

[.console-input]
[source,bash,subs="+macros,+attributes"]
----
curl -X POST localhost:8080/add/point -d="{name:'Null',description:'Null Island',coordinates:[0,0]}"
----

Reload the map to look for your new Point.
