= Backstage Workshop at Red Hat Summit 2023
:page-layout: home

[#introduction]
== An Internal Developer Platform (IDP)

Every team and every project evolves a tailored development environment. This collection of tools, services and configuration is often maintained by convention and transmitted by osmosis.

IDPs help teams curate, manage and replicate these environments. Backstage is an open source CNCF project for building developer platforms, and for encapsulating tools, services, documentation and best practices in “golden paths” to ease onboarding and daily development work.

In this end-to-end developer experience, you’ll start on a golden path we’ve paved to show how Red Hat products center on the OpenShift Container Platform to supply a complete foundation for cloud-native development.

You will build and deploy a three-tier web application. You’ll be guided into OpenShift DevSpaces, a web-based Integrated Development Environment (IDE), to view and modify source code. OpenShift GitOps will automate the build, test and deploy cycle as you iterate your application with new features or fixes.

Backstage will support you from the start with signposts to components in a single place connecting the three key developer views: an IDE to code, pipelines to build, and orchestration to deploy your application.

== Backstage Glossary

Enough Backstage to use it.

* Create+ in left nav
* _Template_ selection
* Catalog: Entities
* Deployed _Components_

[.tiles.browse]
== Workshop Outline

[.tile]
.xref:01-setup.adoc[OpenShift and Backstage Authentication]
* xref:01-setup.adoc#prerequisites[Prerequisites]
* xref:01-setup.adoc#cluster_access[Accessing OpenShift]
* xref:01-setup.adoc#backstage_access[Accessing Backstage]

[.tile]
.xref:02-templates.adoc[Software Templates]
* xref:02-templates.adoc#templates[Templates and Golden Paths]
* xref:02-templates.adoc#frontend[Deploy the Front End Template]
* xref:02-templates.adoc#github[View the resulting Repos]
* xref:02-templates.adoc#gateway[Deploy the Gateway Template]
* xref:02-templates.adoc#pipelines[View the resulting Pipelines]
* xref:02-templates.adoc#view_map[Access the resulting Workloads]

[.tile]
.xref:03-components.adoc[Components]
* xref:03-components.adoc#software_catalog[Software Catalog]
* xref:03-components.adoc#component_frontend[View the FrontEnd Component]
* xref:03-components.adoc#plugins[Plugins]
* xref:03-components.adoc#component_gateway[View the Gateway Component]
* xref:03-components.adoc#backend[Deploy the Backend Template]
* xref:03-components.adoc#backend_view[View the Backend Component]
* xref:03-components.adoc#configuration[Service Binding and Configuration]

[.tile]
.xref:04-development.adoc[Development]
* xref:04-development.adoc#devspaces[OpenShift DevSpaces]
* xref:04-development.adoc#gateway_update[Update the Gateway Component]
* xref:04-development.adoc#validate_changes[Validate your Changes]
