apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: ${{values.namespace}}-${{values.component_id}}-dev
  {%- if values.description %}
  description: ${{values.description}}
  {%- endif %}
  annotations:
    argocd/app-name: ${{values.namespace}}-${{values.component_id}}-dev
    backstage.io/kubernetes-id: ${{values.namespace}}-${{values.component_id}}-dev
    backstage.io/kubernetes-namespace: ${{values.namespace}}
    backstage.io/kubernetes-label-selector: 'app.kubernetes.io/instance=${{values.namespace}}-${{values.component_id}}-dev'
    backstage.io/techdocs-ref: dir:.
    janus-idp.io/tekton-enabled : 'false'
    github.com/project-slug: ${{values.githubOrg}}/${{values.repoName}}
  tags:
    - typescript
    - angular
    - workshop
  links:
    - url: https://console-openshift-console${{values.cluster_id}}/dev-pipelines/ns/${{values.namespace}}/
      title: Pipelines
      icon: web
    - url: https://console-openshift-console${{values.cluster_id}}/k8s/ns/${{values.namespace}}/deployments/${{values.component_id}}
      title: Deployment
      icon: web
    - url: https://devspaces${{values.cluster_id}}/#https://github.com/${{values.githubOrg}}/${{values.repoName}}?che-editor=che-incubator/che-code/latest&devfilePath=.devfile-vscode.yaml
      title: OpenShift Dev Spaces (VS Code)
      icon: web
    - url: http://${{values.component_id}}-${{values.namespace}}${{values.cluster_id}}
      title: Map
      icon: web
spec:
  type: service
  lifecycle: production
  owner: ${{values.owner | dump}}
  system: workshop-system-${{values.namespace}}
  consumesApis:
    - gateway-api-${{values.namespace}}
---
apiVersion: backstage.io/v1alpha1
kind: System
metadata:
  name: workshop-system-${{values.namespace}}
  tags:
    - backstage
    - janus-idp
    - openshift
    - workshop
    - rh-summit
spec:
  owner: ${{values.owner | dump}}
